version: 2.1
orbs:
  salesforce-sfdx: circleci/salesforce-sfdx@1.0.0
jobs:
  install_authenticate:
    executor: sfdx/default
    steps:
      - checkout
      - sfdx/install
      - sfdx/auth:
          defaultusername: soh@edi.com
      - run:
        command:
          sfdx force:auth:list
        name: Run your SFDX commands here
workflows:
  basic-test:
    jobs:
      - install_authenticate
